import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Box, Container, CssBaseline } from "@mui/material";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/app/ui/theme";
import Header from "@/app/ui/Header";
import { ReactNode } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <AppRouterCacheProvider>
            <CssBaseline enableColorScheme />
            <main>{children}</main>
          </AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
